#!/bin/bash

#  __________________
# | App Name Section |
#  ------------------

#define icons for window
icontheme=$(grep -o "gtk-icon-theme-name.*" ~/.config/gtk-3.0/settings.ini | cut -d "=" -f 2)

active_win() {
    if [[ ${1:0:14} == "activewindow>>" ]]; then
        string=${1:14}
        class="${string/,*/}"
        title=${string/,/ \| }
        icon=$(geticons "$class" -s 16 -c 1 -t "$icontheme" --no-fallbacks | head -n 1 2>/dev/null);
        if [[ "$title" == " | " ]]; then unset title;
        else 
            if [[ -z "$icon" ]]; then icon="$HOME/.config/eww/icons/hyprland.png"; fi
        fi
        echo '{"title":"'$title'","icon":"'$icon'"}'
    fi  
}

socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | 
while read -r event; do active_win "$event"; done

