#!/bin/bash

#  _______________
# | Audio Control |
#  ---------------

## Get Volume info

pactl subscribe | rg --line-buffered "on sink" | while read -r line; do
    PERCENT=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}'| sed 's/%//')
    MUTE=$(pactl get-sink-mute @DEFAULT_SINK@ | grep "Mute:" | cut -d ' ' -f2)
    SNK=$(pactl list sinks | grep -oP '(?<=Active Port: ).*')
    if [[ "$MUTE" == "no" ]]; then
      if [[ "$SNK" == "analog-output-headphones" ]]; then 
        SNK="H"
        ICON="󰋋"
      else
        SNK="S" 
        ICON="" 
      fi
    else
      if [[ "$SNK" == "analog-output-headphones" ]]; then ICON="󰟎"
      else ICON=""; fi
  	fi
    
    # Json format
    echo '{"status":"'$MUTE'","perc":"'$PERCENT'","icon":"'$ICON'","sink":"'$SNK'"}'
done