#!/bin/bash

#  _________________
# | Battery Control |
#  -----------------

## Get Battery info
while true; do
  BAT=$(ls /sys/class/power_supply | grep -m 1 BAT)

  if [[ -n "$BAT" ]]; then
    BATSTATUS="$(cat /sys/class/power_supply/${BAT}/status)"
    BATVAL="$(cat /sys/class/power_supply/${BAT}/capacity)"

    if [[ "$BATSTATUS" == "Discharging" ]];then
      if [ "$BATVAL" -gt 90 ];then ICON="󰂂"
      elif [ "$BATVAL" -gt 80 ];then ICON="󰂁"
      elif [ "$BATVAL" -gt 70 ];then ICON="󰂀"
      elif [ "$BATVAL" -gt 60 ];then ICON="󰁿"
      elif [ "$BATVAL" -gt 50 ];then ICON="󰁾"
      elif [ "$BATVAL" -gt 40 ];then ICON="󰁽"
      elif [ "$BATVAL" -gt 30 ];then ICON="󰁼"
      elif [ "$BATVAL" -gt 20 ];then ICON="󰁻"
      elif [ "$BATVAL" -gt 10 ];then ICON="󰁺"
      elif [ "$BATVAL" -gt 0 ];then ICON="󰂎"; fi
    else ICON="󰂄"; fi
    BATVAL="${BATVAL}%"
    sleep_duration=2
  else
    BATVAL="PC-"
    BATSTATUS="Plugged"
    ICON="󰇅"
    sleep_duration=60
  fi

  # Json format
  echo '{"capacity":"'$BATVAL'","status":"'$BATSTATUS'","icon":"'$ICON'"}'
  sleep $sleep_duration
done