#!/bin/bash

#  ___________________
# | Bluetooth Control |
#  -------------------

## Get bluetooth info
while true; do
    power_state=$(bluetoothctl show | grep "Powered:" | cut -d ' ' -f 2)
    connected_devices=$(bluetoothctl devices Connected | cut -d ' ' -f 3-)
    if [[ "$power_state" == "yes" ]]; then
        if [[ -z "$connected_devices" ]]; then
            status="on"
            icon="󰂯"
            sleep_duration=2
            connected_devices="No device"
        else
            status="connected"
            icon="󰂱"
            sleep_duration=2
        fi
    else
        status="off"
        icon="󰂲"
        sleep_duration=4
        connected_devices="Off"
    fi
    
    # Json format
    echo '{"status":"'$status'","name":"'$connected_devices'","icon":"'$icon'"}'
    sleep $sleep_duration
done
   
