#!/bin/bash

#  ________________________
# | Brightness Control Bar |
#  ------------------------

## Get Brightness
udevadm monitor | rg --line-buffered "backlight" | while read -r line; do
    echo $(brightnessctl get)
done

