#!/bin/bash

#  ____________
# | Cava bars |
#  -----------

# Conf stdout
conf="[general]\nframerate=60\nbars = 10\n[output]\nmethod = raw\nraw_target = /dev/stdout\ndata_format = ascii\nascii_max_range = 7\n"

echo -en "$conf" | cava -p /dev/stdin | awk -F';' '{
  NF--;  # Delete last char
  printf "{\"bars\": \"[";
  for (i = 1; i <= NF; i++) {
    printf "%s", $i;
    if (i < NF) printf ",";
  }
  printf "]\"}\n";
  fflush();
}'
