#!/bin/bash

#  __________________
# | Choose Wallpaper |
#  ------------------

## Global vars
source ${HOME}/.config/rofi/scripts/globalcontrol.sh

# set dir wallpapers
wallPath=~/wallpapers

# Set current directory wallpapers
cd $wallPath || exit

# Get path wallpaper selected
WalSel=$(yad --title="Choose wallpaper" --file --image-filter --add-preview --large-preview --button=yad-cancel:1 --text-align=center --text "<span font_style='oblique' font_stretch='expanded'>Choose wallpaper </span>")

# Get name wallpaper
walname="${WalSel##*/}"
walname="${walname%.*}"

# apply wallpaper
if [[ -n "${WalSel}" ]] ; then
    if [[ -z "$(hyprctl -j clients | jaq -c '.[].workspace.id')" ]]; then
        killall io.elementary.desktop.agent-polkit &> /dev/null
        eww close menu_opt music calendar &> /dev/null
	    eww update open_music=false open_cal=false open_menu=false &> /dev/null
        matugen -q -m ${color_mode} image ${WalSel}
        killall dunst &> /dev/null
        sed -i "s/icon_theme = .*/icon_theme = \"${current_icon}\"/" ~/.config/dunst/dunstrc
        killall xdg-desktop-portal-gtk &> /dev/null
        /usr/lib/policykit-1-pantheon/io.elementary.desktop.agent-polkit &
        notify-send "t1" -a "${walname} 󰲍" -i "$WalSel" -r 91190 -t 2200
    else
        notify-send -u critical "${WARNING_TL}" "${WARNING_MS}" -t 3600
    fi
fi

