#!/bin/bash

#  _________________
# | Change Font Eww |
#  -----------------

# Current font
currentFont=$(grep -o "gtk-font-name.*" ~/.config/gtk-3.0/settings.ini | cut -d "=" -f 2)

# Select font
font_select=$(yad --font --title="Font Chooser" --fontname="$currentFont")

if [[ -n "$font_select" ]]; then
    gsettings set org.gnome.desktop.interface font-name "'$font_select'"
    sed -i "s/gtk-font-name=.*/gtk-font-name=$font_select/" ~/.config/gtk-3.0/settings.ini
fi