#!/bin/bash

#  ________________________
# | Update Keyboard Layout |
#  ------------------------

# Directory conf file
conf_dir=~/.config/hypr/conf/input.conf

# Get layout list - ouput on json format
layout_list=$(cat $conf_dir | grep 'kb_layout*' | cut -d '=' -f2 | sed 's/ //g')
IFS=',' read -ra layout_array <<< "$layout_list"
layout_count=${#layout_array[@]}

# Data on json and list availables layouts
if [[ -n "$layout_list" && "$layout_count" -gt 1 ]]; then
    for ((i = 0; i < layout_count; i++)); do
        json+=$(echo '{"name":"'${layout_array[i]}'","id":'$i'}')
        layout_avl+="$(sed -n '/! layout/,/! variant/ {/! layout/d;/! variant/d;p}' /usr/share/X11/xkb/rules/base.lst | grep -w ''${layout_array[i]}''),"
    done
fi

# Verifications
check_layout(){
    if [[ -z "$layout_list" ]]; then
        sed -i 's/kb_layout = */kb_layout = us/g' $conf_dir
        notify-send "Layout 󰌌" "Void a keyboard layout. Adding 'English' layout and exiting..."
        exit 0
    elif [[ "$layout_count" -eq 1 ]]; then
        notify-send "Layout 󰌌" "Only one keyboard layout. Exiting..."
        exit 0
    fi
}

# Select layout availables
select_layout(){
    layout_choose=$(echo "$layout_avl" | tr ',' '\n' | yad --title="Choose item" --list --column="<span font_style='oblique' font_stretch='expanded'>Keyboard Layouts</span>" --separator=" " --text-align=center --text="<b>KEYBOARD LAYOUTS LIST</b>")
    layout_select=$(echo "$layout_choose" | awk '{print $1}')
    lan=$(echo "$layout_choose" | awk '{print $2}')
    get_id=$(echo $json | jq -c 'select(.name=="'${layout_select}'") | .id')
    if [[ -z "$get_id" ]]; then exit 0; fi
}

# ------Add language------
add_layout(){
    kb_list=$(sed -n '/! layout/,/! variant/ {/! layout/d;/! variant/d;p}' /usr/share/X11/xkb/rules/base.lst |
    yad --title="Choose item" --list --column="<span font_style='oblique' font_stretch='expanded'>Keyboard Layout Availables (Language)</span>" \
    --separator=" " --text-align=center --text="<b>KEYBOARD LAYOUT LIST AVAILABLE</b>")

    chosen_layout=$(echo $kb_list | awk '{print $1}')
    chosen_lan=$(echo $kb_list | awk '{print $2}')

    get_name=$(echo $json | jq -c 'select(.name=="'${chosen_layout}'") | .name')

    if [[ -n $kb_list ]]; then
        if [[ -z $get_name ]]; then
            original=$(cat $conf_dir | grep 'kb_layout*')
            change=$(cat $conf_dir | grep 'kb_layout*' | sed "s/$/,$chosen_layout/")
            sed -i "s|$original|$change|g" $conf_dir
            notify-send "t2" -a "Layout 󰌌" "<span size='large'>Add layout: $chosen_lan [$chosen_layout]</span>" -i " " -r 9125
        else
            notify-send "Layout 󰌌" "Layout already exist"
        fi
    fi
}

# ------Delete language------
del_layout(){
    # Call func
    check_layout
    select_layout

    # Pos layout
    if [[ $get_id -ne 0 ]]; then
        original=$(cat $conf_dir | grep 'kb_layout*')
        change=$(cat $conf_dir | grep 'kb_layout*' | sed "s/,$layout_select//")
    else
        original=$(cat $conf_dir | grep 'kb_layout*')
        change=$(cat $conf_dir | grep 'kb_layout*' | sed "s/$layout_select,//")
    fi

    # Apply change
    sed -i "s|$original|$change|g" $conf_dir
    notify-send "t2" -a "Layout 󰌌" "<span size='large'>Delete layout: $lan [$layout_select]</span>" -i " " -r 9125
}

# ------Switcher Layout------
swt_layout(){
    #Check
    check_layout

    # Current Device
    currentDevice=$(hyprctl -j devices | jq -c '.keyboards.[] | select(.main==true) | .name' | sed 's/"//g')

    # List available devices
    devices=$(hyprctl -j devices | jq -c '.keyboards.[] | .name' | sed 's/"//g')

    # Sort the list according to the current device
    sortedDevice=$(echo "$devices" | grep "^$currentDevice$"; echo "$devices" | grep -v "^$currentDevice$" | sort)
    sortedDevice=$(echo "$sortedDevice" | tr '\n' '!')

    # Current Layouts
    currentLayout=$(hyprctl -j devices | jq -c '.keyboards.[] | select(.main==true) | .active_keymap' | sed 's/"//g')
    currentLayout=$(sed -n '/! layout/,/! variant/ {/! layout/d;/! variant/d;p}' /usr/share/X11/xkb/rules/base.lst | grep -w "${currentLayout}")
    currentLayout=$(echo "$currentLayout" | awk '{print $1}')

    # List available layouts
    layouts=($(hyprctl -j devices | jq -c '.keyboards.[] | select(.main==true) | .layout' | sed 's/"//g' | sed "s/,//g"))
    layouts=$(printf "%s\n" "${layouts[@]}")

    # Sort the list according to the current layout
    sortedLayout=$(echo "$layouts" | grep "^$currentLayout$"; echo "$layouts" | grep -v "^$currentLayout$" | sort)
    sortedLayout=$(echo "$sortedLayout" | tr '\n' '!')

    # Options
    options=$(yad --title="KB Settings" --text-align=center --text="<b>KEYBOARD LANGUAGE SETTINGS </b>" --form \
            --field="Device 󰌌::CB" "$sortedDevice" --field="Language ::CB" "$sortedLayout")

    if [[ -n $options ]]; then
        device=$(echo $options | cut -d "|" -f1)
        layout=$(echo $options | cut -d "|" -f2)

        [[ -z $device ]] && exit 0
        [[ -z $layout ]] && exit 0

        id_layout=$(echo $json | jq -c 'select(.name=="'${layout}'") | .id')

        # Switching
        hyprctl -q switchxkblayout $device $id_layout
        sleep 1
        language=$(hyprctl -j devices | jq -c '.keyboards.[] | select(.main==true) | .active_keymap' | sed 's/"//g' | awk '{print $1}')
        notify-send "t2" -a "Layout 󰌌" "<span size='medium'>Kb: $device\nLayout: $language [$layout]</span>" -i " " -r 9125
    fi
}

case $1 in
    -a) add_layout ;;
    -d) del_layout ;;
    -s) swt_layout ;;
    *) echo "Error. Command Not Found"
esac