#!/bin/sh

#  ______________
# | Open Bar EWW |
#  --------------

STATUS_FILE=~/.cache/eww_status

## Run eww daemon if not running already
if [[ ! -f $STATUS_FILE ]]; then
	touch $STATUS_FILE
	eww daemon
	sleep 2s
	eww open ewwBar
fi