#!/bin/bash

#  _______________
# | Music Control |
#  ---------------

## Get data
STATUS="$(playerctl status)"

## Get status
get_status() {
	if [ "$(playerctl status)" = "Playing" ]; then
		echo "󱖒"
	else
		echo "󱖑"
	fi
}

## Get song
get_song() {
	song="$(playerctl metadata xesam:title)"
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist="$(playerctl metadata xesam:artist)"
	if [[ -z "$artist" ]]; then
		echo "Play any song 󰎆"
	else
		echo "$artist"
	fi	
}


## Get cover
get_cover() {
	if [ "$STATUS" = "Playing" ] || [ "$STATUS" == "Paused" ];then
		echo "$(playerctl metadata mpris:artUrl)"
	else
	    echo "$HOME/.config/eww/icons/music.png"
	fi
}

## Toggle status
toggle() {
  playerctl play-pause
}

## Next
next() {
  playerctl next
}

## Previous
previous() {
  playerctl previous
}

## Execute accordingly
case $1 in
    --song) get_song ;;
	--artist) get_artist ;;
	--status) get_status ;;
	--cover) get_cover ;;
	--toggle) toggle ;;
	--next) next ;;
	--prev) previous ;;
esac