#!/bin/bash

#  _______________
# | Music Control |
#  ---------------

## Get data
while true; do
    title=$(playerctl -s metadata -f '{{title}}')
    artist=$(playerctl -s metadata -f '{{artist}}')
    cover=$(playerctl -s metadata -f '{{mpris:artUrl}}')
    status=$(playerctl -s metadata -f '{{status}}')
    minInit=$(playerctl -s metadata -f '{{duration(position)}}')
    minEnd=$(playerctl -s metadata -f '{{duration(mpris:length)}}')
    namePlayer=$(playerctl -s metadata -f '{{playerName}}')
    countPlayers=$(playerctl -s -a metadata -f '{{playerName}}' | wc -l)
    scale=0
    position=0
    circular=0
    
    if [[ -n "${minEnd}" ]]; then
        scale=$(playerctl metadata -f '{{mpris:length}}' | awk '{ print int($1/1000000) }')
        position=$(playerctl metadata -f '{{position}}' | awk '{ print int($1/1000000) }')
        circular=$(awk -v pos="$position" -v sc="$scale" 'BEGIN { printf("%.2f", (pos / sc) * 100) }')
    else
        title="No media"
        artist="Offline"
        cover="icons/music.svg"
        namePlayer="no player"
        minInit=$minEnd
    fi

    if [[ -z "$title" ]]; then title="Uknown"; fi
    if [[ -z "$namePlayer" ]]; then namePlayer="Uknown"; fi
    if [[ -z "$artist" ]]; then artist="Uknown"; fi
    if [[ -z "$cover" ]]; then cover="icons/music.svg"; fi
    
    if [[ "$status" == "Playing" ]]; then
        status=""
        icon=""
    else
        status=""
        icon=""
    fi
    JSON_STRING=$( jq -n \
        --arg title " $title" \
        --arg artist "$artist" \
        --arg cover "$cover" \
        --arg status "$status" \
        --arg minInit "$minInit" \
        --arg minEnd "$minEnd" \
        --arg scale "$scale" \
        --arg position "$position" \
        --arg circular "$circular" \
        --arg icon "$icon" \
        --arg player "󰎆 $namePlayer" \
        --arg count "$countPlayers" \
        '{title: $title, artist: $artist, cover: $cover, status: $status, minInit: $minInit, minEnd: $minEnd, scale: $scale, circular: $circular, position: $position, icon: $icon, player: $player, count: $count}' )
    echo $JSON_STRING
    sleep 1s
done