#!/bin/bash

#  _________________________
# | General Network Control |
#  -------------------------

## Get network info
while true; do
	SIGNAL=$(nmcli -t -f in-use,signal dev wifi | grep "*:*" | sed "s/*://")
	TYPE=$(nmcli -t -f type con show --active | head -n1 | sed 's/.*-//g')
  	NET=$(nmcli -t -f name con show --active | head -n1 | sed 's/\"/\\"/g')

	if [[ "$TYPE" == "wireless" ]]; then
		if [[ "$SIGNAL" -gt 80 ]]; then ICON="󰤨"
		elif [[ "$SIGNAL" -gt 60 ]]; then ICON="󰤥"
		elif [[ "$SIGNAL" -gt 40 ]]; then ICON="󰤢"
		elif [[ "$SIGNAL" -gt 20 ]]; then ICON="󰤟"
		elif [[ "$SIGNAL" -eq 0 ]]; then ICON="󰤫"; fi
		TYPE="WI-FI"
		sleep_duration=2
	elif [[ "$TYPE" == "ethernet" ]]; then 
		ICON="󰈀"
		NET="Plugged"
		sleep_duration=6
	else
		ICON="󰤭"
		TYPE="Internet"
		NET="Offline"
		sleep_duration=4
	fi
	
	# Json format
	echo '{"type":"'$TYPE'","name":"'$NET'","icon":"'$ICON'"}'
	sleep $sleep_duration
done