#!/bin/bash

#  _______________
# | Power Control |
#  ---------------

## Global vars
source $HOME/.config/rofi/scripts/globalcontrol.sh

_verify(){
    if [ -n "$(hyprctl -j clients | jaq -c '.[].workspace.id')" ]; then
        notify-send -u critical "${WARNING_TL}" "${WARNING_MS}"
        exit 0
    else
	    eww close power reboot logout lock cancel &> /dev/null
        sleep 0.1
    fi
}

_close(){
    eww close power reboot logout lock cancel &> /dev/null
    eww update rev_power=false rev_reboot=false rev_logout=false rev_lock=false rev_cancel=false &> /dev/null
}

_open(){
    if [[ -z $(hyprctl layers | grep -o "power_layer") ]]; then
        eww open-many power reboot logout lock cancel &> /dev/null
    else
        _close
    fi
}

case $1 in
    -r)  _verify && systemctl reboot ;;
    -l)  _verify && hyprctl dispatch exit ;;
    -c)  _close ;;
    -p)  _verify && systemctl poweroff ;;
    *)  _open ;;
esac