#!/bin/bash

#  _____________________
# | Change color scheme |
#  ---------------------

source $HOME/.config/rofi/scripts/globalcontrol.sh

switch_clr(){
	if [ "$(hyprctl clients | grep -c 'Window')" -eq "0" ]; then
		if [[ "$current_theme" -eq "0" ]]; then
			killall polkit-gnome-authentication-agent-1
			sed -i -e "s|'./scss/bar-light.scss';|'./scss/bar.scss';|" -e "s|'./scss/bar1-light.scss';|'./scss/bar1.scss';|" ~/.config/eww/eww.scss
			gsettings set org.gnome.desktop.interface color-scheme prefer-dark
			sed -i "s/gtk-application-prefer-dark-theme=.*/gtk-application-prefer-dark-theme=1/" ~/.config/gtk-3.0/settings.ini
			/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
			gsettings set org.gnome.gedit.preferences.editor scheme 'ayu'
			killall dunst
			#sed -i '2s/colors-kitty-light.conf/colors-kitty.conf/' ~/.config/kitty/kitty.conf
			#sed -i -e '5s/background/foreground/' -e '6s/foreground/background/' ~/.config/foot/foot.ini
			sed -i '2s/MateriaLight/MateriaDark/' ~/.config/Kvantum/kvantum.kvconfig
			sed -i -e '445, 454 s/foreground/background/' -e '461s/foreground/background/' ~/.config/dunst/dunstrc
			sed -i -e '446, 455 s/background/foreground/' -e '462s/background/foreground/' ~/.config/dunst/dunstrc
			if [[ -d ~/.vscode-oss/extensions/dlasagno.wal-theme* ]]; then
				mv ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template.js ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template-dr.js
				mv ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template-lt.js ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template.js
				mv ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template-dr.js ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template-lt.js
			fi
			dunstify "t1" -a "Cambiando a tema oscuro  ..." -t 2200
		else
			killall polkit-gnome-authentication-agent-1
			sed -i -e "s|'./scss/bar.scss';|'./scss/bar-light.scss';|" -e "s|'./scss/bar1.scss';|'./scss/bar1-light.scss';|" ~/.config/eww/eww.scss
			gsettings set org.gnome.desktop.interface color-scheme prefer-light
			sed -i "s/gtk-application-prefer-dark-theme=.*/gtk-application-prefer-dark-theme=0/" ~/.config/gtk-3.0/settings.ini
			/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
			gsettings set org.gnome.gedit.preferences.editor scheme 'catppuccin_latte'
			killall dunst
			#sed -i '2s/colors-kitty.conf/colors-kitty-light.conf/' ~/.config/kitty/kitty.conf
			#sed -i -e '5s/foreground/background/' -e '6s/background/foreground/' ~/.config/foot/foot.ini
			sed -i '2s/MateriaDark/MateriaLight/' ~/.config/Kvantum/kvantum.kvconfig
			sed -i -e '445, 454 s/background/foreground/' -e '461s/background/foreground/' ~/.config/dunst/dunstrc
			sed -i -e '446, 455 s/foreground/background/' -e '462s/foreground/background/' ~/.config/dunst/dunstrc
			if [[ -d ~/.vscode-oss/extensions/dlasagno.wal-theme* ]]; then
				mv ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template.js ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template-dr.js
				mv ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template-lt.js ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template.js
				mv ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template-dr.js ~/.vscode-oss/extensions/dlasagno.wal-theme-1.1.2-universal/out/template-lt.js
			fi
			dunstify "t1" -a "Cambiando a tema claro  ..." -t 2200
		fi
	else
		dunstify -u critical "ADVERTENCIA - Cierre todas las ventanas antes de cambiar de tema" -t 3600
	fi
}

get_icon(){
	if [[ "$current_theme" -eq "0" ]]; then
		echo "󰨙"
	else
		echo "󰨚"
	fi
}

if [ "$1" = "--icon" ]; then
  	get_icon
else #default
  	switch_clr
fi
