#!/bin/bash

#  ________________
# | Power Profiles |
#  ----------------

gdbus monitor --system --dest org.freedesktop.UPower.PowerProfiles | while read -r line; do
    profile_state=$(powerprofilesctl get)
    if [[ "$profile_state" == "performance" ]]; then
        icon="󰓅"
        profile="Performance"
    elif [[ "$profile_state" == "balanced" ]]; then
        icon="󰾅"
        profile="Balanced"
    else
        icon="󰾆"
        profile="Power-Saver"
    fi
    echo '{"profile":"'$profile'","icon":"'$icon'"}'
done
