#!/bin/bash

# Get a list of available wifi connections and morph it into a nice-looking list
wifi_list=$(nmcli -f "SECURITY,SSID" device wifi list | sed 1d | sed 's/  */ /g' | sed -E "s/WPA*.?\S/󰤪 /g" | sed "s/^--/󱛏 /g" | sed "s/󰤪  󰤪/󰤪/g" | sed "/--/d")

connected=$(echo $(nmcli -f WIFI g))
if [[ "$connected" = "WIFI activado" ]]; then
	toggle="󰤭  Turn off"
elif [[ "$connected" = "WIFI desactivado" ]]; then
	toggle="󰤨  Turn on"
fi

# Use rofi to select wifi network
chosen_network=$(echo -e "$toggle\n$wifi_list" | uniq -u | rofi -config $HOME/.config/rofi/wifi.rasi -dmenu -i -selected-row 1 -p "Wi-Fi SSID: " )
# Get name of connection
read -r chosen_id <<< "${chosen_network:3}"

if [ "$chosen_network" = "" ]; then
	exit
elif [ "$chosen_network" = "󰤨  Turn on" ]; then
	notify-send -i $HOME/.config/eww/icons/wifi_on.png "Wifi activado 󰤯 "
	nmcli radio wifi on
elif [ "$chosen_network" = "󰤭  Turn off" ]; then
	notify-send -i $HOME/.config/eww/icons/wifi_off.png "Wifi desactivado 󰤮 "
	nmcli radio wifi off
else
	# Message to show when connection is activated successfully
  	success_message="Conexión exitosa a \"$chosen_id\"."
	# Get saved connections
	saved_connections=$(nmcli -g NAME connection)
	if [[ $(echo "$saved_connections" | grep -w "$chosen_id") = "$chosen_id" ]]; then
		nmcli connection up id "$chosen_id" | grep "successfully" && notify-send "󱚽 " "$success_message"
	else
		if [[ "$chosen_network" =~ "󰤪" ]]; then
			wifi_password=$(rofi -config $HOME/.config/rofi/wifiPSW.rasi -dmenu -p "󱦄 󰌌 : " )
		fi
		nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "󱚽  " "$success_message"
    fi
fi
