#!/bin/bash

#  ______________
# | Wifi Control |
#  --------------

# Get current ssid
current_ssid=$(nmcli -t -f IN-USE,SSID device wifi list | grep '*' | cut -d ":" -f2)

# Init array
wifi_list=()

# Save networks into array
while read -r line; do
    wifi_list+=("$line")
done < <(nmcli -f "SECURITY,SSID" device wifi list | sed 1d | sed 's/  */ /g' | sed -E "s/WEP*.?\S/󰤪 /g" | sed -E "s/WPA*.?\S/󰤪 /g" | sed "s/^--/󱛏 /g" | sed "s/󰤪  󰤪/󰤪/g" | sed "/--/d" | awk '!seen[$0]++')

# Sorted networks
IFS=$'\n' sorted_wifi_list=($(printf "%s\n" "${wifi_list[@]}" | sort))

# Init vars
ids=()
names=()
buf=""

# Read array sorted and build output
for i in "${!sorted_wifi_list[@]}"; do
    ssid_name=$(echo "${sorted_wifi_list[$i]}" | sed -E 's/^[^ ]+ *//')  # Limpiar el SSID
    
    if [[ "$ssid_name" == "$current_ssid" ]]; then
        name="${sorted_wifi_list[$i]}"
        icon=""
        class="item_pnl_btn_current"
        tooltip="Connected"
    else
        name="${sorted_wifi_list[$i]}"
        icon=""
        class="item_pnl_btn"
        tooltip="Available"
    fi

    if [[ "${name}" =~ "󰤪" ]]; then type="protected";
    else type="open"; fi
    
    buf="$buf (box :orientation \"h\" :halign \"fill\" :class \"bx_pnl_item\" \
        (label :halign \"start\" :class \"item_pnl_name\" :text \"$name\") \
        (button :halign \"end\" :class \"$class\" :tooltip \"$tooltip\" :onclick \"./scripts/set_wifi '${ssid_name}' '${type}' '${class}'&\" \"$icon\"))"

done

eww update wifi_list="(box :orientation \"v\" :halign \"fill\" :valign \"start\" :vexpand true :hexpand true $buf)"
