#!/bin/bash

#  ____________________
# | Workspaces Control |
#  --------------------

move_ws(){
    activeID=$(hyprctl -j activeworkspace | jaq -c '.id')
    usedIDs=($(hyprctl -j workspaces | jaq -c '.[] | .id'))
    totalws=(0 0 0 0 0 0 0 0 0 0) #default ws 10
    #dynamicws=$(hyprctl workspaces -j | jq -c 'length') #Dynamic open ws

    for ws_id in "${usedIDs[@]}"; do
        if [ $ws_id -le 10 ]; then
            totalws[$(( ws_id - 1 ))]=2
        fi
    done

    totalws[$(( activeID - 1 ))]=1

    JSON_STRING=$(printf '%s\n' "${totalws[@]}" |
    jaq -R -s -c 'split("\n") | map(select(length > 0) | tonumber)')
    echo $JSON_STRING
}

socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | 
while read -r event; do move_ws; done
