#Theme
include ./themes/colors-kitty.conf

#General
font_family		JetBrainsMono Nerd Font
font_size		15
bold_font		auto
italic_font		auto
bold_italic_font	url
auto_style		curly
disable_ligatures	never
window_padding_width 	20
cursor_trail 1

#Close unconfirm
confirm_os_window_close 0
