#  ___________________________
# | Hyprland - General Config |
#  ---------------------------

# ---Monitors----
source = ./conf/monitors.conf

# ---Init exec---
source = ./conf/exec.conf

# ---Colors---
source = ./conf/colors-hyprland.conf

# ---Environment---
source = ./conf/env.conf

# ---Input---
source = ./conf/input.conf

# ---General---
source = ./conf/general.conf

# ---Decorations---
source = ./conf/decoration.conf

# ---Animations---
source = ./conf/animation.conf

# ---Layouts---
source = ./conf/layout.conf

# ---Window rules---
source = ./conf/windowrule.conf

# ---Layer rules---
source = ./conf/layerrule.conf

# ---Keybinds---
source = ./conf/binds.conf

# ---Workspaces rules---
source = ./conf/workspacerule.conf