#!/bin/bash

#  ________________________________
# | Set wallpaper on shared screen |
#  --------------------------------

# Wallpaper
current_wal=$(cat ~/.cache/wal/colors.json | jq ".wallpaper" | sed 's/"//g')

if [[ "$(hyprctl monitors -j | jq '.[] | .id' | wc -l)" -ge 2 ]]; then
    swww img -o "HDMI-A-1" $current_wal
	eww open ewwBar1
else
    swww init
fi