#!/bin/bash

#  ________________________________
# | Set wallpaper on shared screen |
#  --------------------------------

if [ "$(hyprctl monitors | grep -c Monitor)" -ge "2" ]; then
    current_wal=$(echo "$(swww query)" | grep -o 'image:.*' | awk '{print $2}')
    swww img -o "HDMI-A-1" $current_wal
	eww open status_bar1 
else
    swww query && swww init
fi