#!/bin/bash

#  ________________________________
# | Set wallpaper on shared screen |
#  --------------------------------

# Colors pywal (path wallpaper)
source "${HOME}/.cache/wal/colors.sh"

if [ "$(hyprctl monitors -j | jq '.[] | .id' | wc -l)" -ge 2 ]; then
    swww img -o "HDMI-A-1" $wallpaper
	eww open ewwBar1
else
    swww init
fi