cursor {{colors.on_background.default.hex}}
cursor_text_color {{colors.on_background.default.hex}}

foreground            {{colors.on_background.default.hex}}
background            {{colors.background.default.hex}}
selection_foreground  {{colors.on_primary_container.default.hex}}
selection_background  {{colors.primary_container.default.hex}}
url_color             {{colors.source_color.default.hex}}

# black
color8   {{colors.outline.default.hex}}
color0   {{colors.background.default.hex}}

# red
color1   {{colors.primary.default.hex}}
color9   {{colors.primary.default.hex}}

# green
color2   {{colors.primary.default.hex | auto_lightness: 10.0}}
color10  {{colors.primary.default.hex | auto_lightness: 10.0}}

# yellow
color3   {{colors.secondary.default.hex}}
color11  {{colors.secondary.default.hex}}

# blue
color4  {{colors.secondary.default.hex | auto_lightness: 10.0}}
color12 {{colors.secondary.default.hex | auto_lightness: 10.0}}

# magenta
color5   {{colors.tertiary.default.hex}}
color13  {{colors.tertiary.default.hex}}

# cyan
color6   {{colors.tertiary.default.hex | auto_lightness: 10.0}}
color14  {{colors.tertiary.default.hex | auto_lightness: 10.0}}

# white
color15   {{colors.on_background.default.hex}}
color7  {{colors.on_background.default.hex}}