# Shell variables
# Generated by 'wal'
wallpaper='{{image}}'

# Special
background='{{colors.background.default.hex}}'
foreground='{{colors.on_background.default.hex}}'
cursor='{{colors.on_background.default.hex}}'

# Colors
color0='{{colors.background.default.hex}}'
color1='{{colors.primary.default.hex}}'
color2='{{colors.primary.default.hex | auto_lightness: 10.0}}'
color3='{{colors.secondary.default.hex}}'
color4='{{colors.secondary.default.hex | auto_lightness: 10.0}}'
color5='{{colors.tertiary.default.hex}}'
color6='{{colors.tertiary.default.hex | auto_lightness: 10.0}}'
color7='{{colors.on_background.default.hex}}'
color8='{{colors.outline.default.hex}}'
color9='{{colors.primary.default.hex}}'
color10='{{colors.primary.default.hex | auto_lightness: 10.0}}'
color11='{{colors.secondary.default.hex}}'
color12='{{colors.secondary.default.hex | auto_lightness: 10.0}}'
color13='{{colors.tertiary.default.hex}}'
color14='{{colors.tertiary.default.hex | auto_lightness: 10.0}}'
color15='{{colors.on_background.default.hex}}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
